format_version: 10
pipelines:
  Test1:
    group: AT20_Graphql
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    secure_variables:
      SONAR_TOKEN: AES:BZKuFNen4zAfwGhpaVOjAg==:CJvY4wCTBClAVZIlu2Effb2WdxiD+rwpJ4S9jd3BQGaITagQhWJH0F78Re7Bhisa
    materials:
      git-3705b1f:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        shallow_clone: false
        auto_update: true
        branch: task10_wjvq
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - script: |
                npm install
                npm test
            artifacts:
            - build:
                source: tests/report.html
                destination: html_report
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - script: |
                ls -la
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.organization=at20graphql -Dsonar.projectKey=at20graph -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io'