format_version: 10
pipelines:
  test1:
    group: AT20Group
    label_template: '${COUNT}'
    lock_behavior: none
    materials:
      git-8387a00:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        shallow_clone: false
        auto_update: true
        branch: task9
    stages:
      - Test:
          fetch_materials: true
          clean_workspace: false
          jobs:
            - npm-install:
                docker_image: node:18-alpine3.16
                command: npm install
            - npm-test:
                docker_image: node:18-alpine3.16
                command: npm test
          tasks:
            - exec:
                command: echo 'Placeholder for post actions'
      - CodeInspection:
          fetch_materials: true
          clean_workspace: false
          jobs:
            - sonarqube-scanner:
                docker_image: sonarsource/sonar-scanner-cli
                command: |
                  sonar-scanner \
                    -Dsonar.organization=at20-graphql \
                    -Dsonar.projectKey=at20-PRFV \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=https://sonarcloud.io
          tasks:
            - exec:
                command: echo 'Placeholder for post actions'
      - QualityGate:
          fetch_materials: false
          clean_workspace: false
          jobs:
            - quality-gate:
                command: |
                  def qg = waitForQualityGate()
                  sh "echo ${qg.status}"
                  if (qg.status != 'OK') {
                    error "Pipeline aborted due to quality gate failure: ${qg.status}"
                  }