format_version: 10
pipelines:
  Test1_PRFV:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    secure_variables:
      SONAR_TOKEN: AES:xnVn4V0VRSLmeCg0brgFVw==:TcR5TV9NLSahvX7x8XdGgo9ZN6y4+j83KWK1EqGxFitaZpMM6t6Sal89EtTZc2SS
      DOCKER_PASS: AES:fCtSAljmKxE6i1x2JJ2GYw==:bXqOZCLb4FL9N74jGYhdyA==
    materials:
      git-91ca77d:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        username: prfv
        shallow_clone: false
        auto_update: true
        branch: task11_prfv
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                npm install
                npm test
            artifacts:
            - build:
                source: tests/report.html
                destination: html_report
            - build:
              source: Dockerfile
            - build :
              source: docker-compose.prfv.yaml
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                ls -la
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.organization=at20-graphql -Dsonar.projectKey=at20-PRFV -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
    - PackageAndPublish:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          PackageAndPublish:
            timeout: 0
            resources:
            - docker
            tasks:
            - fetch:
                is_file: true
                source: docker-compose.prfv.yaml
                stage: Test1_PRFV
                job: unit-test
                run_if: passed
            - script: |
                docker build -t at20_graphql .
                docker login -u pprfv -p ${DOCKER_PASS}
                docker tag at20_graphql pprfv/pprfv:${GIT_COMMIT_HASH}
                docker push pprfv/pprfv:${GIT_COMMIT_HASH}
            artifacts:
            - build:
                source: docker-compose.prfv.yaml
  SmokeTest:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    materials:
      Test1_PRFV:
        pipeline: Test1_PRFV
        stage: PackageAndPublish
    stages:
    - DeployToDev:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          DeployDev:
            timeout: 0
            resources:
            - docker
            tasks:
            - fetch:
              pipeline: Test1_PRFV
              stage: PackageAndPublish
              job: PackageAndPublish
              source: docker-compose.prfv.yaml
              is_file: true
              run_if: passed
            - script: |
                echo deploy here
                ls -la

  # Pull the images needed in the docker-compose.yaml
  # Deploy in dev
  # Run the test
