format_version: 10
pipelines:
  Testwjvq:
    group: AT20_Graph
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3705b1f:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        shallow_clone: false
        auto_update: true
        branch: task10_wjvq
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - script: |
                curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
                sudo apt install nodejs
                npm test
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner comand h
                command: echo
                run_if: passed
