format_version: 10
pipelines:
  test1:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-8387a00:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        shallow_clone: false
        auto_update: true
        branch: task9
    stages:
    - stage1: Test
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          - name: RunTests
            tasks:
              - exec:
                  command: npm install
              - exec:
                  command: npm test
            artifacts:
              - tests/report.html
              - test/jest-html-reporters-attach/*

    - stage2: CodeInspection
        jobs:
          - name: RunCodeInspection
            tasks:
              - exec:
                  command: sonar-scanner \
                            -Dsonar.organization=at20-graphql \
                            -Dsonar.projectKey=at20-PRFV \
                            -Dsonar.sources=. \
                            -Dsonar.host.url=https://sonarcloud.io