format_version: 10
pipelines:
  Test1_PRFV:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    secure_variables:
      SONAR_TOKEN: AES:7teoZBs1X+ry3gHucPUk7g==:tmLBfq97i/8WLstIAQ91qA==
    materials:
      git-91ca77d:
        git: https://github.com/AT20-DevOps/AT_20_GRAPHQL_SERVICE.git
        username: prfv
        shallow_clone: false
        auto_update: true
        branch: task11_prfv
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                npm install
                npm test
            artifacts:
            - build:
                source: tests/report.html
                destination: html_report
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                ls -la
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner  -Dsonar.organization=at20-graphql -Dsonar.projectKey=at20-PRFV -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io'

